### ISSUE TITLE
It is Giving me this error

### ISSUE THREAD

**Issue by lakshya3612** [wangsongyuan98/flappybird3#1]
hi! i am getting this error
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\FlappyBird_And_OpenCV-master 2\FlappyBird_And_OpenCV-master\flappy.py", line 8, in <module>
    import detecteyes
  File "C:\Users\hp\Downloads\FlappyBird_And_OpenCV-master 2\FlappyBird_And_OpenCV-master\detecteyes.py", line 65, in <module>
    if not face_cascade.load(cv.samples.findFile(face_cascade_name)):
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\core\src\utils\samples.cpp:62: error: (-2:Unspecified error) OpenCV samples: Can't find required data file: C:/Users/wangs/PycharmProjects/opencv/data/haarcascades/haarcascade_frontalface_alt.xml in function 'cv::samples::findFile'

please tell me what can i do now

**Comment by maxwangsongyuan** [comment]
Thanks for the question. I think you need to download the haarcascade_frontalface_alt dataset from OpenCV's official website(i did not upload it to GitHub because the file size is very large). With this trained dataset, your camera will then be able to accurately register your facial movement.

**Comment by maxwangsongyuan** [comment]
this is a good resource for your reference: https://docs.opencv.org/3.4/db/d28/tutorial_cascade_classifier.html
